name: Laravel Tests

on:
  push:
    branches:
      - main

jobs:
  laravel_tests:
    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:latest
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: marcus
          MYSQL_PASSWORD: Muasa@2020New
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Laravel Tests
        run: vendor/bin/phpunit

  react-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run React Tests
        run: npm test
